[package]
authors = ["Timothy Meade <zt.tmzt@gmail.com>"]
build = "build.rs"
name = "isymtope"
version = "0.2.0"

[build-dependencies]
lalrpop = "0.13.1"

[dependencies]
broadcast = "0.1.0"
difference = "1.0.0"
error-chain = "0.10.0"
hyper = "0.11.0"
indoc = "0.1.15"
itertools = "0.6.0"
lalrpop-util = "0.13.1"
linked-hash-map = "0.5.0"
wren = "0.1.12"

[dependencies.uuid]
features = ["v4"]
version = "0.5.1"
