[package]
authors = ["Timothy Meade <zt.tmzt@gmail.com>"]
name = "isymtope"
version = "0.3.0"

[dependencies.isymtope-build]
path = "./isymtope-build"

[dependencies.isymtope-server]
path = "./isymtope-server"

[workspace]
