[package]
authors = ["Timothy Meade <zt.tmzt@gmail.com>"]
name = "isymtope"
version = "0.3.0"

[dependencies.isymtope-build]
default-features = false
path = "./isymtope-build"

[dependencies.isymtope-server]
optional = true
path = "./isymtope-server"

[dependencies.isymtope-wasm]
path = "./isymtope-wasm"

[features]
server = ["isymtope-server"]

[workspace]

[profile.release]
opt-level = "s"
debug = false