[package]
authors = ["Timothy Meade <zt.tmzt@gmail.com>"]
name = "ismytope"
version = "0.1.0"

[dependencies]
error-chain = "0.10.0"
hyper = "0.11.0"
itertools = "0.6.0"
lalrpop-util = "0.13.1"
uuid = { version = "0.5.1", features = ["v4"] }
wren = "0.1.10"
