[package]
authors = ["Timothy Meade <zt.tmzt@gmail.com>"]
build = "build.rs"
name = "isymtope"
version = "0.1.0"

[build-dependencies]
lalrpop = "0.13.1"

[dependencies]
error-chain = "0.10.0"
hyper = "0.11.0"
itertools = "0.6.0"
lalrpop-util = "0.13.1"
wren = "0.1.12"

[dependencies.uuid]
features = ["v4"]
version = "0.5.1"
