[package]
authors = ["Timothy Meade <zt.tmzt@gmail.com>"]
name = "isymtope"
version = "0.3.0"

[dependencies.wasm-log]
optional = true
path = "./wasm-log"

[dependencies.isymtope-ast-common]
optional = true
path = "./isymtope-ast-common"

[dependencies.isymtope-build]
default-features = false
optional = true
path = "./isymtope-build"

[dependencies.isymtope-server]
optional = true
path = "./isymtope-server"

[dependencies.isymtope-wasm]
optional = true
path = "./isymtope-wasm"

[features]
server = ["isymtope-server"]
[profile.release]
debug = true
opt-level = 2
[replace."rand:0.3.20"]
path = "./wasm-rand"

[workspace]
