[package]
authors = ["Timothy Meade <zt.tmzt@gmail.com>"]
name = "isymtope-wasm"
version = "0.1.0"

[dependencies.isymtope-build]
default-features = false
path = "../isymtope-build/"

[lib]
crate-type = ["cdylib"]
path = "src/lib.rs"

[replace]
"rand:0.3.20" = { path = "../wasm-rand" }
