[package]
authors = ["Timothy Meade <zt.tmzt@gmail.com>"]
build = "build.rs"
name = "isymtope-build"
version = "0.3.0"

[dependencies]
failure = "0.1.1"
itertools = "0.6.0"
lalrpop-util = "0.14.0"
lazy_static = "0.2.11"
linked-hash-map = "0.5.0"
log = "0.4.1"
regex = "0.2.2"
serde_json = "1.0.6"
trimmer = "0.3.5"

[build-dependencies.lalrpop]
version = "0.14.0"

[dependencies.uuid]
features = ["v4"]
optional = true
version = "0.5.1"

[dependencies.time]
optional = true
version = "0.1.39"

[features]
default = ["uuid_v4", "session_time"]
uuid_v4 = ["uuid"]
session_time = ["time"]
extern_rand = []
include_templates = []
